[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["league-exp-util"]

[tool.setuptools.dynamic]
version = {attr = "league-exp-util.__version__"}